music/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),  #
    path('ranking/', include('ranking.urls')),
    path('play/', include('play.urls')),
    path('comment/', include('comment.urls')),
    path('search/', include('search.urls')),
    path('user/', include('user.urls')),
    path('upload/',include('upload.urls')),
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

play/urls.py
from django.urls import path
from . import views
urlpatterns = [
    # 歌曲播放页面
    path('<int:song_id>.html', views.playView, name='play'),
]

upload/urls.py
from django.contrib import admin
from django.urls import path
from .views import upload

urlpatterns = [
    path("",upload,name = "upload")
]

index/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField('分类',max_length=100)
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name

class Audio(models.Model):
    song_name = models.CharField('歌名',max_length=70)
    singer = models.CharField('歌手',max_length=100)
    category = models.ManyToManyField(Category, verbose_name='分类')
    song_image = models.ImageField(upload_to='pic/',verbose_name='歌曲封面')
    song_file = models.FileField(upload_to = 'audio/', verbose_name = '源文件')
    song_lrc = models.FileField(upload_to = 'lrc/', verbose_name = '源文件')
    upload_user = models.CharField('分享用户',max_length=50)
    song_release = models.CharField('发行时间', max_length=20)
    #下面为新增代码
    class Meta:
        verbose_name = '音乐'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.song_name


# 歌曲动态表dynamic
class Dynamic(models.Model):
    song = models.ForeignKey(Audio, on_delete=models.CASCADE, verbose_name='歌名')
    dynamic_plays = models.IntegerField('播放次数')
    dynamic_search = models.IntegerField('搜索次数')
    class Meta:
        # 设置Admin界面的显示内容
        verbose_name = '歌曲动态'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.song.song_name

# 歌曲点评表comment
class Comment(models.Model):
    comment_id = models.AutoField('序号', primary_key=True)
    comment_text = models.CharField('内容', max_length=500)
    comment_user = models.CharField('用户', max_length=20)
    song = models.ForeignKey(Audio, on_delete=models.CASCADE,verbose_name='歌名')
    comment_date = models.CharField('日期', max_length=50)
    class Meta:
        # 设置Admin界面的显示内容
        verbose_name = '歌曲评论'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.comment_user
# Create your models here.

upload/models.py
from django.db import models

# Create your models here.

upload/views.py
import datetime
from django.shortcuts import render,redirect
from .form import SaveAudio
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/user/login')
def upload(request):
    username = request.user.username
    if request.method == 'GET':
        form = SaveAudio()
        return render(request,'upload.html',locals())
    form = SaveAudio(request.POST, request.FILES)
    print(form)
    if form.is_valid():
        tips = "上传成功"
        form.save()
        return render(request,'upload.html',locals())
    tips = "上传失败"
    return render(request, 'upload.html', locals())

upload/templates/upload.html
{% extends "title_base.html" %}
{% load static %}
{% block header_extends %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/upload.css' %}">
{% endblock %}

{% block content %}
    <div class="upload-box">
        <div class="upload-title">
            <h3>音乐分享</h3>
        </div>
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="song_name" class="upload-label">音乐名:</label>
                <div class="upload-input" style="width: 30%">
                    {{ form.song_name }}
                </div>
            </div>
            <div class="form-group">
                <label for="singer" class="upload-label">歌手:</label>
                <div class="upload-input" style="width: 30%">
                    {{ form.singer }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_category" class="upload-label">分类</label>
                <div class="upload-input">{{ form.category }}</div>
                <p style="padding-left: 38%;font-size: 10px">按住 Control 键或 Mac 上的 Command 键来选择多项。</p>
            </div>
            <div class="form-group">
                <label for="exampleInputFile1" class="upload-label">封面:</label>
                <div class="upload-input">{{ form.song_image }}</div>
            </div>
            <div class="form-group">
                <label for="exampleInputFile3" class="upload-label">歌词</label>
                <div class="upload-input">{{ form.song_lrc }}</div>
            </div>
            <div class="form-group">
                <label for="exampleInputFile2" class="upload-label">源文件</label>
                <div class="upload-input">{{ form.song_file }}</div>
            </div>
            {% if tips %}
                <div style="color: red;margin-left: 38%">提示:<span>{{ tips }}</span></div>
            {% endif %}
            <div style="display: none">
                {{ form.upload_user }}
                {{ form.song_release }}
            </div>
            <div class="form-group" style="padding: 20px 45% 20px 45%;">
                <div class="col-sm-offset-2 col-sm-10">
                    <button id="upload_btn" type="submit" class="btn btn-default"
                            style="background-color: #0b95ea; color: white;font-weight: bold">分享
                    </button>
                </div>
            </div>

        </form>

    </div>
    <script type="text/javascript" src="{% static 'js/plugins/jquery.min.js' %}"></script>
    <script>
        document.getElementById('id_song_release').value = gettime();
        document.getElementById('id_upload_user').value = "{{ username }}";

        function gettime() {
            var mydate = new Date();
            var year = mydate.getFullYear();
            var month = mydate.getMonth() + 1;
            var day = mydate.getDay();
            var hour = mydate.getHours();
            var minute = mydate.getMinutes();
            var time = year + '年' + month + '月' + day + '日' + hour + ':' + minute;
            return time;
        }

    </script>

{% endblock %}